### PR TITLE
fix: #1040

### LINKED ISSUE #1040: [LLSE - QJS] QuickJS插件中 一定情况下在try...catch 块外执行 throw 引起崩溃
### 异常模块

ScriptEngine (脚本引擎)

### 操作系统

Windows 10

### LiteLoader 版本

2.9.2

### BDS 版本

1.19.51

### 发生了什么?

创建如下插件
```js
try {
    let limitfile = new JsonConfigFile(`./plugins/test/limit.json`);
    limitObj = JSON.parse(limitfile.read());
} catch (error) {
    log(error)
    logger.error(`It can work to here`);
    throw Error()
}
```
在`./plugins/test/limit.json`中填写
```json


}
```
启动服务端
发生崩溃

另外 在最早发现这个问题的插件里，如果在此处以下一个不包含llse的api的try...catch中引发异常并抛出不会造成崩溃

CrashLogger输出
[Crash.zip](https://github.com/LiteLDev/LiteLoaderBDS/files/10481585/Crash.zip)

测试使用的插件和其他必要文件
[plugins.zip](https://github.com/LiteLDev/LiteLoaderBDS/files/10481608/plugins.zip)

### 复现此问题的步骤

见“发生了什么”

### 有关的日志/输出

```raw
00:09:54 INFO [PreLoader] Loading symbols from pdb...
00:09:56 INFO [PreLoader] Fast Dlsym Loaded <477204>
00:09:56 INFO [PreLoader] LiteLoader.dll Injected.


          _     _ _       _                    _
         | |   (_) |_ ___| |    ___   __ _  __| | ___ _ __
         | |   | | __/ _ \ |   / _ \ / _` |/ _` |/ _ \ '__|
         | |___| | ||  __/ |__| (_) | (_| | (_| |  __/ |
         |_____|_|\__\___|_____\___/ \__,_|\__,_|\___|_|

       --------   Light-Weight BDS Plugin Loader   ----------


00:09:56 INFO [LiteLoader] 加载原生插件...
00:09:56 INFO [LiteLoader] 原生插件 <LLMoney.dll> 已加载
00:09:56 INFO [LiteLoader] * Js 脚本引擎已加载
00:09:56 INFO [LiteLoader] * Lua 脚本引擎已加载
00:09:56 INFO [LiteLoader] * NodeJs 脚本引擎已加载
00:09:56 INFO [LLMoney] Loaded version: 2.9.0
00:09:56 INFO [LiteLoader] ScriptEngine initializing...
00:09:56 INFO [LiteLoader] 依赖项 BaseLib.lua 已加载。
00:09:56 INFO [LiteLoader] 加载 Lua 插件...
00:09:56 INFO [LiteLoader] 0 个 Lua 插件已加载。
00:09:56 INFO [LiteLoader] 依赖项 BaseLib.js 已加载。
00:09:56 INFO [LiteLoader] 加载 Js 插件...
00:09:56 ERROR [LiteLoader] Fail to parse json content in file!
00:09:56 ERROR [LiteLoader] [json.exception.parse_error.101] parse error at line 3, column 1: syntax error while parsing value - unexpected '}'; expected '[', '{', or a literal
00:09:56 INFO [index] {message:unexpected token: '}',fileName:<input>,lineNumber:3,stack:    at <input>:3
    at parse (native)
    at <eval> (./plugins/index.js:4)
}
00:09:56 ERROR [index] It can work to here

[Crashed!]
-- Unhandled Exception in -> ucrtbase.dll
-- Exception Code: 0xC0000409
-- Minidump generated in Directory ./logs/Crash

[StackTrace] Function abort at 0x7FFD84DD2820  [ucrtbase.dll<6.2.19041.789>]
[StackTrace] Function terminate at 0x7FFD84DD1F80  [ucrtbase.dll<6.2.19041.789>]
[StackTrace] Function _NLG_Return2 at 0x7FFD75A01150  [VCRUNTIME140_1.dll<14.34.31931.0>]
[StackTrace] Function _NLG_Return2 at 0x7FFD75A01150  [VCRUNTIME140_1.dll<14.34.31931.0>]
[StackTrace] Function _NLG_Return2 at 0x7FFD75A01150  [VCRUNTIME140_1.dll<14.34.31931.0>]
[StackTrace] Function _CxxFrameHandler4 at 0x7FFD75A040A0  [VCRUNTIME140_1.dll<14.34.31931.0>]
[StackTrace] Function _chkstk at 0x7FFD87412300  [ntdll.dll<6.2.19041.2130>]
[StackTrace] Function RtlRaiseException at 0x7FFD873C1070  [ntdll.dll<6.2.19041.2130>]
[StackTrace] Function KiUserExceptionDispatcher at 0x7FFD87410F20  [ntdll.dll<6.2.19041.2130>]
[StackTrace] Function RaiseException at 0x7FFD84E8CCC0  [KERNELBASE.dll<6.2.19041.2364>]
[StackTrace] Function CxxThrowException at 0x7FFD75A16690  [VCRUNTIME140.dll<14.34.31931.0>]
[StackTrace] Function ???????? at 0x7FFD00733007  [LiteLoader.Js.dll<2.9.2.0>]
[StackTrace] Function ???????? at 0x7FFD0072C0D4  [LiteLoader.Js.dll<2.9.2.0>]
[StackTrace] Function ???????? at 0x7FFD00727038  [LiteLoader.Js.dll<2.9.2.0>]
[StackTrace] Function ???????? at 0x7FFD00788B59  [LiteLoader.Js.dll<2.9.2.0>]
[StackTrace] Function ???????? at 0x7FFD007852EA  [LiteLoader.Js.dll<2.9.2.0>]
[StackTrace] Function onPostInit at 0x7FFD009732E0  [LiteLoader.Js.dll<2.9.2.0>]
[StackTrace] Function onPostInit at 0x7FFD009732E0  [LiteLoader.Js.dll<2.9.2.0>]
[StackTrace] Function onPostInit at 0x7FFD009732E0  [LiteLoader.Js.dll<2.9.2.0>]
[StackTrace] Function onPostInit at 0x7FFD009732E0  [LiteLoader.Js.dll<2.9.2.0>]
[StackTrace] Function onPostInit at 0x7FFD009732E0  [LiteLoader.Js.dll<2.9.2.0>]
[StackTrace] Function onPostInit at 0x7FFD009732E0  [LiteLoader.Js.dll<2.9.2.0>]
[StackTrace] Function onPostInit at 0x7FFD009732E0  [LiteLoader.Js.dll<2.9.2.0>]
[StackTrace] Function onPostInit at 0x7FFD009732E0  [LiteLoader.Js.dll<2.9.2.0>]
[StackTrace] Function onPostInit at 0x7FFD009732E0  [LiteLoader.Js.dll<2.9.2.0>]
[StackTrace] Function onPostInit at 0x7FFD009732E0  [LiteLoader.Js.dll<2.9.2.0>]
[StackTrace] Function ???????? at 0x7FFD0096FE96  [LiteLoader.Js.dll<2.9.2.0>]
[StackTrace] Function ???????? at 0x7FFD0096D8D8  [LiteLoader.Js.dll<2.9.2.0>]
[StackTrace] Function ???????? at 0x7FFD00972DBA  [LiteLoader.Js.dll<2.9.2.0>]
[StackTrace] Function ll::LoadMain at 0x7FFD20BFBE60  [LiteLoader.dll<2.9.2.0>]
-- At File D:\a\LiteLoaderBDS\LiteLoaderBDS\LiteLoader\src\liteloader\Loader.cpp : Line 323
[StackTrace] Function liteloaderMain at 0x7FFD20BF73C0  [LiteLoader.dll<2.9.2.0>]
-- At File D:\a\LiteLoaderBDS\LiteLoaderBDS\LiteLoader\src\liteloader\LiteLoader.cpp : Line 362
[StackTrace] Function THookTemplate<1745144914232631845,238647026>::_hook at 0x7FFD20BF7ED0  [LiteLoader.dll<2.9.2.0>]
-- At File D:\a\LiteLoaderBDS\LiteLoaderBDS\LiteLoader\src\liteloader\LiteLoader.cpp : Line 400
[StackTrace] Function __scrt_common_main_seh at 0x7FF728CBD69C  [bedrock_server_mod.exe<1.19.51.01>]
[StackTrace] Function BaseThreadInitThunk at 0x7FFD85D97600  [KERNEL32.DLL<6.2.19041.2364>]
[StackTrace] Function RtlUserThreadStart at 0x7FFD873C2680  [ntdll.dll<6.2.19041.2130>]
```

### 插件列表

```raw
仅测试插件 ll各组件 llmoney2.9.0
以下为去除测试插件后的插件列表

00:17:09 INFO [Server] - LLMoney [v2.9.0] (LLMoney.dll)
00:17:09 INFO [Server]   EconomyCore for LiteLoaderBDS
00:17:09 INFO [Server] - ScriptEngine-Lua [v2.9.2] (LiteLoader.Lua.dll)
00:17:09 INFO [Server]   Lua ScriptEngine for LiteLoaderBDS
00:17:09 INFO [Server] - PermissionAPI [v2.9.0] (PermissionAPI.dll)
00:17:09 INFO [Server]   Builtin & Powerful permission API for LiteLoaderBDS
00:17:09 INFO [Server] - ScriptEngine-QuickJs [v2.9.2] (LiteLoader.Js.dll)
00:17:09 INFO [Server]   Javascript ScriptEngine for LiteLoaderBDS
00:17:09 INFO [Server] - ScriptEngine-NodeJs [v2.9.2] (LiteLoader.NodeJs.dll)
00:17:09 INFO [Server]   Node.js ScriptEngine for LiteLoaderBDS
```

### PR DESCRIPTION
**Pull request by cryx233**
## Description

fix crash when loading wrong json config file

## Issues fixed

Close #1040

### CODE REVIEW

**Review by ShrBox — DISMISSED** [review]

File: ScriptEngine/src/api/DataAPI.cpp [hunk 1]
```diff
@@ -251,7 +251,13 @@ bool ConfJsonClass::reload() {
     if (!jsonTexts)
         return false;
 
-    jsonConf = fifo_json::parse(*jsonTexts, nullptr, true, true);
+    try {
+        jsonConf = fifo_json::parse(*jsonTexts, nullptr, true, true);
+    } catch (...){
```
Comment (Jaciezyt) [inline ScriptEngine/src/api/DataAPI.cpp]:
```suggestion
    } catch (...) {
```

**Review by Jaciezyt — CHANGES_REQUESTED** [review]

**Review by Jaciezyt — APPROVED** [review]

**Review by ShrBox — APPROVED** [review]
