### PR TITLE
Fix Event::MobSpawnEvent #930

### LINKED ISSUE #930: LLSE中监听实体自然生成的BUG
### 异常模块

ScriptEngine (脚本引擎)

### 操作系统

Windows 10

### LiteLoader 版本

2.9.0-beta-1

### BDS 版本

1.19.50

### 发生了什么?

刷怪笼因亮度无法刷怪时会一直尝试生成实体，此接口也会一直被回调！

### 复现此问题的步骤

`mc.listen("onMobSpawn", (typeName, pos) => {
    log(pos, typeName)
    return false;
})`

然后放置一个刷怪笼并在附近放上火把。

### 有关的日志/输出

_No response_

### 插件列表

_No response_

### PR DESCRIPTION
**Pull request by KobeBryant114514**
## Description

1. Fix Event::MobSpawnEvent #930
2. Add ev.mMob parameter into Event::MobSpawnEvent

## Issues fixed by this PR
Close #930 

## Type of changes

- [x] Bug fix
- [x] New feature 
- [x] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://docs.litebds.com/#/zh_CN/Maintenance/README)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

### CODE REVIEW

File: LiteLoader/include/llapi/EventAPI.h [hunk 1]
```diff
@@ -680,6 +680,7 @@ class MobSpawnEvent : public EventTemplate<MobSpawnEvent> {
 public:
     string mTypeName;
     Vec3 mPos;
+    Mob* mMob;
```
Comment (ShrBox) [inline LiteLoader/include/llapi/EventAPI.h]: 把`Mob* mMob`放到最后，否则可能造成已有的插件不兼容

Comment (KobeBryant114514) [reply LiteLoader/include/llapi/EventAPI.h]: ok

Comment (KobeBryant114514) [reply LiteLoader/include/llapi/EventAPI.h]: 还有点小问题，我下午改一下重新PR

**Review by ShrBox — APPROVED** [review]
